---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: will-be-replaced
spec:
  maxHistory: 2
  releaseName: th2-release
  interval: 200m
  values:
    component:
      image: will-be-replaced
      name: will-be-replaced
      mqRouter:
        checksum: initial-checksum
        config: will-be-replaced
      grpcRouter:
        checksum: initial-checksum
        config: will-be-replaced
      cradleManager:
        checksum: initial-checksum
        config: will-be-replaced