---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: will-be-replaced
spec:
  resetValues: true
  wait: false
  forceUpgrade: true
  releaseName: th2-core-box
  chart:
    secretRef:
      name: git-chart-creds
    skipDepUpdate: true
  values:
    component:
      image: will-be-replaced
      name: will-be-replaced
      mqRouter:
        checksum: initial-checksum
        config: will-be-replaced
      grpcRouter:
        checksum: initial-checksum
        config: will-be-replaced
      cradleManager:
        checksum: initial-checksum
        config: will-be-replaced
