---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: will-be-replaced
spec:
  resetValues: true
  wait: false
  forceUpgrade: true
  releaseName: th2-estore
  chart:
    secretRef:
      name: git-chart-creds
    skipDepUpdate: true
  values:
    component:
      image: will-be-replaced
      name: will-be-replaced