---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: will-be-replaced
spec:
  maxHistory: 2
  resetValues: true
  wait: false
  releaseName: th2-mstore
  chart:
    skipDepUpdate: true
  values:
    component:
      image: will-be-replaced
      name: will-be-replaced
      mqRouter:
        checksum: initial-checksum
        config: will-be-replaced
      grpcRouter:
        checksum: initial-checksum
        config: will-be-replaced
      cradleManager:
        checksum: initial-checksum
        config: will-be-replaced
