name: Build and publish dev release Docker image to Github Container Registry ghcr.io

on: workflow_dispatch

jobs:
  build:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      build-target: 'Docker'
      devRelease: true
      createTag: true
      docker-username: ${{ github.actor }}
      #     FIXME: strict scanner was disabled for 4.6.4 hotfix publishing and must be removed after that
      strict-scanner: false
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}
