name: Dev build and publish Docker images to github registry

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dev-version-*
      - dependabot*
    paths-ignore:
      - README.md

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Docker'
      runsOn: ubuntu-latest
      gradleVersion: '7'
      docker-username: ${{ github.actor }}
#     FIXME: strict scanner was disabled for 4.6.4 hotfix publishing and must be removed after that
      strict-scanner: false
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}