name: Build and publish Docker images to github registry

on:
  push:
    branches:
      - master
      - version-*
    paths:
      - gradle.properties

jobs:
  build:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      build-target: 'Docker'
      runsOn: ubuntu-latest
      gradleVersion: '7'
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}